#!/bin/sh

SCRIPT=`realpath $0`; DIRNAME=`dirname $SCRIPT`

# Do some free space calculations with df and awk
dfk=`df -k /home/mturley`
kbused=`echo "$dfk" | awk 'NR == 2 { print $3 }'`
kbfree=`echo "$dfk" | awk 'NR == 2 { print $4 }'`
gbtotal=`echo "$kbused" "$kbfree" | awk '{ foo = ($1 + $2) / 1024 / 1024 ; print foo }'`
gbused=`echo "$kbused" | awk '{ foo = $1 / 1024 / 1024 ; print foo }'`
gbfree=`echo "$kbfree" | awk '{ foo = $1 / 1024 / 1024 ; print foo }'`
percentused=`echo "$kbused" "$kbfree" | awk '{ print ($1 / ($1 + $2)) * 100 }'`
percentfree=`echo "$kbused" "$kbfree" | awk '{ print ($2 / ($1 + $2)) * 100 }'`

# Make it into something readable
read -r -d '' message << EOM
\`\`\`Used: $gbused / $gbtotal GB ($percentused%)\`\`\`
\`\`\`Available: $gbfree GB ($percentfree%)\`\`\`
EOM

$DIRNAME/send-message "Disk Usage Report" "$message"
