#!/bin/bash

json_escape () {
    printf '%s' "$1" | python -c 'import json,sys; print(json.dumps(sys.stdin.read()))'
}

# Read the URL, and read and escape username and message,
# from command line arguments (json_escape uses a teeny bit of python).
webhook_url="$1"
message_username=`json_escape "$2"`
message_content=`json_escape "$3"`

# Construct a JSON object with those values
json="{\"username\": $message_username, \"content\": $message_content}"

# Send JSON to Discord using curl
curl -H "Content-Type: application/json" \
    -X POST \
    -d "$json" $webhook_url
